
// H2 Database
drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key(id)
);

drop table if exists TB_ADMIN CASCADE;
create table TB_ADMIN
(
    id bigint generated by default as identity,
    user_id varchar(255),
    user_pwd varchar(255),
    user_name varchar(255),
    primary key(id)
);